"""Empirically verified SPAD layouts for predefined maps.

Maps 1-13: device-readback decoded. Map 15 (8x8): AMS Fig 32 + pixel_map.
"""

LAYOUTS = {'3x3_narrow': {'zones': [{'zone_id': 1,
                           'channel': 1,
                           'sub_capture': 0,
                           'spads': [(3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6)],
                           'is_dummy': False},
                          {'zone_id': 2,
                           'channel': 2,
                           'sub_capture': 0,
                           'spads': [(3, 7), (3, 8), (3, 9), (3, 10), (4, 7), (4, 8), (4, 9), (4, 10)],
                           'is_dummy': False},
                          {'zone_id': 3,
                           'channel': 3,
                           'sub_capture': 0,
                           'spads': [(3, 11),
                                     (3, 12),
                                     (3, 13),
                                     (3, 14),
                                     (3, 15),
                                     (4, 11),
                                     (4, 12),
                                     (4, 13),
                                     (4, 14),
                                     (4, 15)],
                           'is_dummy': False},
                          {'zone_id': 4,
                           'channel': 4,
                           'sub_capture': 0,
                           'spads': [(5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)],
                           'is_dummy': False},
                          {'zone_id': 5,
                           'channel': 5,
                           'sub_capture': 0,
                           'spads': [(5, 7), (5, 8), (5, 9), (5, 10), (6, 7), (6, 8), (6, 9), (6, 10)],
                           'is_dummy': False},
                          {'zone_id': 6,
                           'channel': 6,
                           'sub_capture': 0,
                           'spads': [(5, 11),
                                     (5, 12),
                                     (5, 13),
                                     (5, 14),
                                     (5, 15),
                                     (6, 11),
                                     (6, 12),
                                     (6, 13),
                                     (6, 14),
                                     (6, 15)],
                           'is_dummy': False},
                          {'zone_id': 7,
                           'channel': 7,
                           'sub_capture': 0,
                           'spads': [(7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6)],
                           'is_dummy': False},
                          {'zone_id': 8,
                           'channel': 8,
                           'sub_capture': 0,
                           'spads': [(7, 7), (7, 8), (7, 9), (7, 10), (8, 7), (8, 8), (8, 9), (8, 10)],
                           'is_dummy': False},
                          {'zone_id': 9,
                           'channel': 9,
                           'sub_capture': 0,
                           'spads': [(7, 11),
                                     (7, 12),
                                     (7, 13),
                                     (7, 14),
                                     (7, 15),
                                     (8, 11),
                                     (8, 12),
                                     (8, 13),
                                     (8, 14),
                                     (8, 15)],
                           'is_dummy': False}],
                'meta': {'y_size': 6,
                         'x_size': 14,
                         'y_offset_2': 0,
                         'x_offset_2': 0,
                         'time_multiplexed': False,
                         'verified': True,
                         'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '3x3_macro': {'zones': [{'zone_id': 1,
                          'channel': 1,
                          'sub_capture': 0,
                          'spads': [(1, 2),
                                    (1, 3),
                                    (1, 4),
                                    (1, 5),
                                    (1, 6),
                                    (2, 2),
                                    (2, 3),
                                    (2, 4),
                                    (2, 5),
                                    (2, 6),
                                    (3, 2),
                                    (3, 3),
                                    (3, 4),
                                    (3, 5),
                                    (3, 6)],
                          'is_dummy': False},
                         {'zone_id': 2,
                          'channel': 2,
                          'sub_capture': 0,
                          'spads': [(1, 7),
                                    (1, 8),
                                    (1, 9),
                                    (1, 10),
                                    (2, 7),
                                    (2, 8),
                                    (2, 9),
                                    (2, 10),
                                    (3, 7),
                                    (3, 8),
                                    (3, 9),
                                    (3, 10)],
                          'is_dummy': False},
                         {'zone_id': 3,
                          'channel': 3,
                          'sub_capture': 0,
                          'spads': [(1, 11),
                                    (1, 12),
                                    (1, 13),
                                    (1, 14),
                                    (1, 15),
                                    (2, 11),
                                    (2, 12),
                                    (2, 13),
                                    (2, 14),
                                    (2, 15),
                                    (3, 11),
                                    (3, 12),
                                    (3, 13),
                                    (3, 14),
                                    (3, 15)],
                          'is_dummy': False},
                         {'zone_id': 4,
                          'channel': 4,
                          'sub_capture': 0,
                          'spads': [(4, 2),
                                    (4, 3),
                                    (4, 4),
                                    (4, 5),
                                    (4, 6),
                                    (5, 2),
                                    (5, 3),
                                    (5, 4),
                                    (5, 5),
                                    (5, 6),
                                    (6, 2),
                                    (6, 3),
                                    (6, 4),
                                    (6, 5),
                                    (6, 6)],
                          'is_dummy': False},
                         {'zone_id': 5,
                          'channel': 5,
                          'sub_capture': 0,
                          'spads': [(4, 7),
                                    (4, 8),
                                    (4, 9),
                                    (4, 10),
                                    (5, 7),
                                    (5, 8),
                                    (5, 9),
                                    (5, 10),
                                    (6, 7),
                                    (6, 8),
                                    (6, 9),
                                    (6, 10)],
                          'is_dummy': False},
                         {'zone_id': 6,
                          'channel': 6,
                          'sub_capture': 0,
                          'spads': [(4, 11),
                                    (4, 12),
                                    (4, 13),
                                    (4, 14),
                                    (4, 15),
                                    (5, 11),
                                    (5, 12),
                                    (5, 13),
                                    (5, 14),
                                    (5, 15),
                                    (6, 11),
                                    (6, 12),
                                    (6, 13),
                                    (6, 14),
                                    (6, 15)],
                          'is_dummy': False},
                         {'zone_id': 7,
                          'channel': 7,
                          'sub_capture': 0,
                          'spads': [(7, 2),
                                    (7, 3),
                                    (7, 4),
                                    (7, 5),
                                    (7, 6),
                                    (8, 2),
                                    (8, 3),
                                    (8, 4),
                                    (8, 5),
                                    (8, 6),
                                    (9, 2),
                                    (9, 3),
                                    (9, 4),
                                    (9, 5),
                                    (9, 6)],
                          'is_dummy': False},
                         {'zone_id': 8,
                          'channel': 8,
                          'sub_capture': 0,
                          'spads': [(7, 7),
                                    (7, 8),
                                    (7, 9),
                                    (7, 10),
                                    (8, 7),
                                    (8, 8),
                                    (8, 9),
                                    (8, 10),
                                    (9, 7),
                                    (9, 8),
                                    (9, 9),
                                    (9, 10)],
                          'is_dummy': False},
                         {'zone_id': 9,
                          'channel': 9,
                          'sub_capture': 0,
                          'spads': [(7, 11),
                                    (7, 12),
                                    (7, 13),
                                    (7, 14),
                                    (7, 15),
                                    (8, 11),
                                    (8, 12),
                                    (8, 13),
                                    (8, 14),
                                    (8, 15),
                                    (9, 11),
                                    (9, 12),
                                    (9, 13),
                                    (9, 14),
                                    (9, 15)],
                          'is_dummy': False}],
               'meta': {'y_size': 9,
                        'x_size': 14,
                        'y_offset_2': 3,
                        'x_offset_2': 0,
                        'time_multiplexed': False,
                        'verified': True,
                        'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '3x3_macro_v2': {'zones': [{'zone_id': 1,
                             'channel': 1,
                             'sub_capture': 0,
                             'spads': [(4, 2),
                                       (4, 3),
                                       (4, 4),
                                       (4, 5),
                                       (4, 6),
                                       (5, 2),
                                       (5, 3),
                                       (5, 4),
                                       (5, 5),
                                       (5, 6),
                                       (6, 2),
                                       (6, 3),
                                       (6, 4),
                                       (6, 5),
                                       (6, 6)],
                             'is_dummy': False},
                            {'zone_id': 2,
                             'channel': 2,
                             'sub_capture': 0,
                             'spads': [(4, 7),
                                       (4, 8),
                                       (4, 9),
                                       (4, 10),
                                       (5, 7),
                                       (5, 8),
                                       (5, 9),
                                       (5, 10),
                                       (6, 7),
                                       (6, 8),
                                       (6, 9),
                                       (6, 10)],
                             'is_dummy': False},
                            {'zone_id': 3,
                             'channel': 3,
                             'sub_capture': 0,
                             'spads': [(4, 11),
                                       (4, 12),
                                       (4, 13),
                                       (4, 14),
                                       (4, 15),
                                       (5, 11),
                                       (5, 12),
                                       (5, 13),
                                       (5, 14),
                                       (5, 15),
                                       (6, 11),
                                       (6, 12),
                                       (6, 13),
                                       (6, 14),
                                       (6, 15)],
                             'is_dummy': False},
                            {'zone_id': 4,
                             'channel': 4,
                             'sub_capture': 0,
                             'spads': [(7, 2),
                                       (7, 3),
                                       (7, 4),
                                       (7, 5),
                                       (7, 6),
                                       (8, 2),
                                       (8, 3),
                                       (8, 4),
                                       (8, 5),
                                       (8, 6),
                                       (9, 2),
                                       (9, 3),
                                       (9, 4),
                                       (9, 5),
                                       (9, 6)],
                             'is_dummy': False},
                            {'zone_id': 5,
                             'channel': 5,
                             'sub_capture': 0,
                             'spads': [(7, 7),
                                       (7, 8),
                                       (7, 9),
                                       (7, 10),
                                       (8, 7),
                                       (8, 8),
                                       (8, 9),
                                       (8, 10),
                                       (9, 7),
                                       (9, 8),
                                       (9, 9),
                                       (9, 10)],
                             'is_dummy': False},
                            {'zone_id': 6,
                             'channel': 6,
                             'sub_capture': 0,
                             'spads': [(7, 11),
                                       (7, 12),
                                       (7, 13),
                                       (7, 14),
                                       (7, 15),
                                       (8, 11),
                                       (8, 12),
                                       (8, 13),
                                       (8, 14),
                                       (8, 15),
                                       (9, 11),
                                       (9, 12),
                                       (9, 13),
                                       (9, 14),
                                       (9, 15)],
                             'is_dummy': False},
                            {'zone_id': 7,
                             'channel': 7,
                             'sub_capture': 0,
                             'spads': [(10, 2),
                                       (10, 3),
                                       (10, 4),
                                       (10, 5),
                                       (10, 6),
                                       (11, 2),
                                       (11, 3),
                                       (11, 4),
                                       (11, 5),
                                       (11, 6),
                                       (12, 2),
                                       (12, 3),
                                       (12, 4),
                                       (12, 5),
                                       (12, 6)],
                             'is_dummy': False},
                            {'zone_id': 8,
                             'channel': 8,
                             'sub_capture': 0,
                             'spads': [(10, 7),
                                       (10, 8),
                                       (10, 9),
                                       (10, 10),
                                       (11, 7),
                                       (11, 8),
                                       (11, 9),
                                       (11, 10),
                                       (12, 7),
                                       (12, 8),
                                       (12, 9),
                                       (12, 10)],
                             'is_dummy': False},
                            {'zone_id': 9,
                             'channel': 9,
                             'sub_capture': 0,
                             'spads': [(10, 11),
                                       (10, 12),
                                       (10, 13),
                                       (10, 14),
                                       (10, 15),
                                       (11, 11),
                                       (11, 12),
                                       (11, 13),
                                       (11, 14),
                                       (11, 15),
                                       (12, 11),
                                       (12, 12),
                                       (12, 13),
                                       (12, 14),
                                       (12, 15)],
                             'is_dummy': False}],
                  'meta': {'y_size': 9,
                           'x_size': 14,
                           'y_offset_2': -3,
                           'x_offset_2': 0,
                           'time_multiplexed': False,
                           'verified': True,
                           'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '4x4_narrow': {'zones': [{'zone_id': 1,
                           'channel': 1,
                           'sub_capture': 0,
                           'spads': [(1, 2),
                                     (1, 3),
                                     (1, 4),
                                     (1, 5),
                                     (2, 2),
                                     (2, 3),
                                     (2, 4),
                                     (2, 5),
                                     (3, 2),
                                     (3, 3),
                                     (3, 4),
                                     (3, 5)],
                           'is_dummy': False},
                          {'zone_id': 2,
                           'channel': 2,
                           'sub_capture': 0,
                           'spads': [(1, 6), (1, 7), (1, 8), (2, 6), (2, 7), (2, 8), (3, 6), (3, 7), (3, 8)],
                           'is_dummy': False},
                          {'zone_id': 3,
                           'channel': 3,
                           'sub_capture': 0,
                           'spads': [(1, 9), (1, 10), (1, 11), (2, 9), (2, 10), (2, 11), (3, 9), (3, 10), (3, 11)],
                           'is_dummy': False},
                          {'zone_id': 4,
                           'channel': 4,
                           'sub_capture': 0,
                           'spads': [(1, 12),
                                     (1, 13),
                                     (1, 14),
                                     (1, 15),
                                     (2, 12),
                                     (2, 13),
                                     (2, 14),
                                     (2, 15),
                                     (3, 12),
                                     (3, 13),
                                     (3, 14),
                                     (3, 15)],
                           'is_dummy': False},
                          {'zone_id': 5,
                           'channel': 5,
                           'sub_capture': 0,
                           'spads': [(4, 2), (4, 3), (4, 4), (4, 5), (5, 2), (5, 3), (5, 4), (5, 5)],
                           'is_dummy': False},
                          {'zone_id': 6,
                           'channel': 6,
                           'sub_capture': 0,
                           'spads': [(4, 6), (4, 7), (4, 8), (5, 6), (5, 7), (5, 8)],
                           'is_dummy': False},
                          {'zone_id': 7,
                           'channel': 7,
                           'sub_capture': 0,
                           'spads': [(4, 9), (4, 10), (4, 11), (5, 9), (5, 10), (5, 11)],
                           'is_dummy': False},
                          {'zone_id': 8,
                           'channel': 8,
                           'sub_capture': 0,
                           'spads': [(4, 12), (4, 13), (4, 14), (4, 15), (5, 12), (5, 13), (5, 14), (5, 15)],
                           'is_dummy': False},
                          {'zone_id': 9,
                           'channel': 1,
                           'sub_capture': 1,
                           'spads': [(6, 2), (6, 3), (6, 4), (6, 5), (7, 2), (7, 3), (7, 4), (7, 5)],
                           'is_dummy': False},
                          {'zone_id': 10,
                           'channel': 2,
                           'sub_capture': 1,
                           'spads': [(6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8)],
                           'is_dummy': False},
                          {'zone_id': 11,
                           'channel': 3,
                           'sub_capture': 1,
                           'spads': [(6, 9), (6, 10), (6, 11), (7, 9), (7, 10), (7, 11)],
                           'is_dummy': False},
                          {'zone_id': 12,
                           'channel': 4,
                           'sub_capture': 1,
                           'spads': [(6, 12), (6, 13), (6, 14), (6, 15), (7, 12), (7, 13), (7, 14), (7, 15)],
                           'is_dummy': False},
                          {'zone_id': 13,
                           'channel': 5,
                           'sub_capture': 1,
                           'spads': [(8, 2), (8, 3), (8, 4), (8, 5), (9, 2), (9, 3), (9, 4), (9, 5)],
                           'is_dummy': False},
                          {'zone_id': 14,
                           'channel': 6,
                           'sub_capture': 1,
                           'spads': [(8, 6), (8, 7), (8, 8), (9, 6), (9, 7), (9, 8)],
                           'is_dummy': False},
                          {'zone_id': 15,
                           'channel': 7,
                           'sub_capture': 1,
                           'spads': [(8, 9), (8, 10), (8, 11), (9, 9), (9, 10), (9, 11)],
                           'is_dummy': False},
                          {'zone_id': 16,
                           'channel': 8,
                           'sub_capture': 1,
                           'spads': [(8, 12), (8, 13), (8, 14), (8, 15), (9, 12), (9, 13), (9, 14), (9, 15)],
                           'is_dummy': False}],
                'meta': {'y_size': 9,
                         'x_size': 14,
                         'y_offset_2': 3,
                         'x_offset_2': 0,
                         'time_multiplexed': True,
                         'verified': True,
                         'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '4x4_narrow_v2': {'zones': [{'zone_id': 1,
                              'channel': 1,
                              'sub_capture': 0,
                              'spads': [(4, 2), (4, 3), (4, 4), (4, 5), (5, 2), (5, 3), (5, 4), (5, 5)],
                              'is_dummy': False},
                             {'zone_id': 2,
                              'channel': 2,
                              'sub_capture': 0,
                              'spads': [(4, 6), (4, 7), (4, 8), (5, 6), (5, 7), (5, 8)],
                              'is_dummy': False},
                             {'zone_id': 3,
                              'channel': 3,
                              'sub_capture': 0,
                              'spads': [(4, 9), (4, 10), (4, 11), (5, 9), (5, 10), (5, 11)],
                              'is_dummy': False},
                             {'zone_id': 4,
                              'channel': 4,
                              'sub_capture': 0,
                              'spads': [(4, 12), (4, 13), (4, 14), (4, 15), (5, 12), (5, 13), (5, 14), (5, 15)],
                              'is_dummy': False},
                             {'zone_id': 5,
                              'channel': 5,
                              'sub_capture': 0,
                              'spads': [(6, 2), (6, 3), (6, 4), (6, 5), (7, 2), (7, 3), (7, 4), (7, 5)],
                              'is_dummy': False},
                             {'zone_id': 6,
                              'channel': 6,
                              'sub_capture': 0,
                              'spads': [(6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8)],
                              'is_dummy': False},
                             {'zone_id': 7,
                              'channel': 7,
                              'sub_capture': 0,
                              'spads': [(6, 9), (6, 10), (6, 11), (7, 9), (7, 10), (7, 11)],
                              'is_dummy': False},
                             {'zone_id': 8,
                              'channel': 8,
                              'sub_capture': 0,
                              'spads': [(6, 12), (6, 13), (6, 14), (6, 15), (7, 12), (7, 13), (7, 14), (7, 15)],
                              'is_dummy': False},
                             {'zone_id': 9,
                              'channel': 1,
                              'sub_capture': 1,
                              'spads': [(8, 2), (8, 3), (8, 4), (8, 5), (9, 2), (9, 3), (9, 4), (9, 5)],
                              'is_dummy': False},
                             {'zone_id': 10,
                              'channel': 2,
                              'sub_capture': 1,
                              'spads': [(8, 6), (8, 7), (8, 8), (9, 6), (9, 7), (9, 8)],
                              'is_dummy': False},
                             {'zone_id': 11,
                              'channel': 3,
                              'sub_capture': 1,
                              'spads': [(8, 9), (8, 10), (8, 11), (9, 9), (9, 10), (9, 11)],
                              'is_dummy': False},
                             {'zone_id': 12,
                              'channel': 4,
                              'sub_capture': 1,
                              'spads': [(8, 12), (8, 13), (8, 14), (8, 15), (9, 12), (9, 13), (9, 14), (9, 15)],
                              'is_dummy': False},
                             {'zone_id': 13,
                              'channel': 5,
                              'sub_capture': 1,
                              'spads': [(10, 2),
                                        (10, 3),
                                        (10, 4),
                                        (10, 5),
                                        (11, 2),
                                        (11, 3),
                                        (11, 4),
                                        (11, 5),
                                        (12, 2),
                                        (12, 3),
                                        (12, 4),
                                        (12, 5)],
                              'is_dummy': False},
                             {'zone_id': 14,
                              'channel': 6,
                              'sub_capture': 1,
                              'spads': [(10, 6),
                                        (10, 7),
                                        (10, 8),
                                        (11, 6),
                                        (11, 7),
                                        (11, 8),
                                        (12, 6),
                                        (12, 7),
                                        (12, 8)],
                              'is_dummy': False},
                             {'zone_id': 15,
                              'channel': 7,
                              'sub_capture': 1,
                              'spads': [(10, 9),
                                        (10, 10),
                                        (10, 11),
                                        (11, 9),
                                        (11, 10),
                                        (11, 11),
                                        (12, 9),
                                        (12, 10),
                                        (12, 11)],
                              'is_dummy': False},
                             {'zone_id': 16,
                              'channel': 8,
                              'sub_capture': 1,
                              'spads': [(10, 12),
                                        (10, 13),
                                        (10, 14),
                                        (10, 15),
                                        (11, 12),
                                        (11, 13),
                                        (11, 14),
                                        (11, 15),
                                        (12, 12),
                                        (12, 13),
                                        (12, 14),
                                        (12, 15)],
                              'is_dummy': False}],
                   'meta': {'y_size': 9,
                            'x_size': 14,
                            'y_offset_2': -3,
                            'x_offset_2': 0,
                            'time_multiplexed': True,
                            'verified': True,
                            'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '3x3_wide': {'zones': [{'zone_id': 1,
                         'channel': 1,
                         'sub_capture': 0,
                         'spads': [(1, 0),
                                   (1, 1),
                                   (1, 2),
                                   (1, 3),
                                   (1, 4),
                                   (1, 5),
                                   (2, 0),
                                   (2, 1),
                                   (2, 2),
                                   (2, 3),
                                   (2, 4),
                                   (2, 5),
                                   (3, 0),
                                   (3, 1),
                                   (3, 2),
                                   (3, 3),
                                   (3, 4),
                                   (3, 5),
                                   (4, 1),
                                   (4, 3),
                                   (4, 5)],
                         'is_dummy': False},
                        {'zone_id': 2,
                         'channel': 2,
                         'sub_capture': 0,
                         'spads': [(1, 6),
                                   (1, 7),
                                   (1, 8),
                                   (1, 9),
                                   (1, 10),
                                   (1, 11),
                                   (2, 6),
                                   (2, 7),
                                   (2, 8),
                                   (2, 9),
                                   (2, 10),
                                   (2, 11),
                                   (3, 6),
                                   (3, 7),
                                   (3, 8),
                                   (3, 9),
                                   (3, 10),
                                   (3, 11),
                                   (4, 7),
                                   (4, 10)],
                         'is_dummy': False},
                        {'zone_id': 3,
                         'channel': 3,
                         'sub_capture': 0,
                         'spads': [(1, 12),
                                   (1, 13),
                                   (1, 14),
                                   (1, 15),
                                   (1, 16),
                                   (1, 17),
                                   (2, 12),
                                   (2, 13),
                                   (2, 14),
                                   (2, 15),
                                   (2, 16),
                                   (2, 17),
                                   (3, 12),
                                   (3, 13),
                                   (3, 14),
                                   (3, 15),
                                   (3, 16),
                                   (3, 17),
                                   (4, 12),
                                   (4, 14),
                                   (4, 16)],
                         'is_dummy': False},
                        {'zone_id': 4,
                         'channel': 4,
                         'sub_capture': 0,
                         'spads': [(4, 0),
                                   (4, 2),
                                   (4, 4),
                                   (5, 0),
                                   (5, 1),
                                   (5, 2),
                                   (5, 3),
                                   (5, 4),
                                   (5, 5),
                                   (6, 0),
                                   (6, 1),
                                   (6, 2),
                                   (6, 3),
                                   (6, 4),
                                   (6, 5),
                                   (7, 0),
                                   (7, 2),
                                   (7, 4)],
                         'is_dummy': False},
                        {'zone_id': 5,
                         'channel': 5,
                         'sub_capture': 0,
                         'spads': [(4, 6),
                                   (4, 8),
                                   (4, 9),
                                   (4, 11),
                                   (5, 6),
                                   (5, 7),
                                   (5, 8),
                                   (5, 9),
                                   (5, 10),
                                   (5, 11),
                                   (6, 6),
                                   (6, 7),
                                   (6, 8),
                                   (6, 9),
                                   (6, 10),
                                   (6, 11),
                                   (7, 6),
                                   (7, 8),
                                   (7, 9),
                                   (7, 11)],
                         'is_dummy': False},
                        {'zone_id': 6,
                         'channel': 6,
                         'sub_capture': 0,
                         'spads': [(4, 13),
                                   (4, 15),
                                   (4, 17),
                                   (5, 12),
                                   (5, 13),
                                   (5, 14),
                                   (5, 15),
                                   (5, 16),
                                   (5, 17),
                                   (6, 12),
                                   (6, 13),
                                   (6, 14),
                                   (6, 15),
                                   (6, 16),
                                   (6, 17),
                                   (7, 13),
                                   (7, 15),
                                   (7, 17)],
                         'is_dummy': False},
                        {'zone_id': 7,
                         'channel': 7,
                         'sub_capture': 0,
                         'spads': [(7, 1),
                                   (7, 3),
                                   (7, 5),
                                   (8, 0),
                                   (8, 1),
                                   (8, 2),
                                   (8, 3),
                                   (8, 4),
                                   (8, 5),
                                   (9, 0),
                                   (9, 1),
                                   (9, 2),
                                   (9, 3),
                                   (9, 4),
                                   (9, 5),
                                   (10, 0),
                                   (10, 1),
                                   (10, 2),
                                   (10, 3),
                                   (10, 4),
                                   (10, 5)],
                         'is_dummy': False},
                        {'zone_id': 8,
                         'channel': 8,
                         'sub_capture': 0,
                         'spads': [(7, 7),
                                   (7, 10),
                                   (8, 6),
                                   (8, 7),
                                   (8, 8),
                                   (8, 9),
                                   (8, 10),
                                   (8, 11),
                                   (9, 6),
                                   (9, 7),
                                   (9, 8),
                                   (9, 9),
                                   (9, 10),
                                   (9, 11),
                                   (10, 6),
                                   (10, 7),
                                   (10, 8),
                                   (10, 9),
                                   (10, 10),
                                   (10, 11)],
                         'is_dummy': False},
                        {'zone_id': 9,
                         'channel': 9,
                         'sub_capture': 0,
                         'spads': [(7, 12),
                                   (7, 14),
                                   (7, 16),
                                   (8, 12),
                                   (8, 13),
                                   (8, 14),
                                   (8, 15),
                                   (8, 16),
                                   (8, 17),
                                   (9, 12),
                                   (9, 13),
                                   (9, 14),
                                   (9, 15),
                                   (9, 16),
                                   (9, 17),
                                   (10, 12),
                                   (10, 13),
                                   (10, 14),
                                   (10, 15),
                                   (10, 16),
                                   (10, 17)],
                         'is_dummy': False}],
              'meta': {'y_size': 10,
                       'x_size': 18,
                       'y_offset_2': 0,
                       'x_offset_2': 0,
                       'time_multiplexed': False,
                       'verified': True,
                       'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '4x4_wide': {'zones': [{'zone_id': 1,
                         'channel': 1,
                         'sub_capture': 0,
                         'spads': [(1, 0),
                                   (1, 1),
                                   (1, 2),
                                   (1, 3),
                                   (1, 4),
                                   (2, 0),
                                   (2, 1),
                                   (2, 2),
                                   (2, 3),
                                   (2, 4),
                                   (3, 0),
                                   (3, 1),
                                   (3, 2),
                                   (3, 3),
                                   (3, 4)],
                         'is_dummy': False},
                        {'zone_id': 2,
                         'channel': 2,
                         'sub_capture': 0,
                         'spads': [(1, 5),
                                   (1, 6),
                                   (1, 7),
                                   (1, 8),
                                   (2, 5),
                                   (2, 6),
                                   (2, 7),
                                   (2, 8),
                                   (3, 5),
                                   (3, 6),
                                   (3, 7),
                                   (3, 8)],
                         'is_dummy': False},
                        {'zone_id': 3,
                         'channel': 3,
                         'sub_capture': 0,
                         'spads': [(1, 9),
                                   (1, 10),
                                   (1, 11),
                                   (1, 12),
                                   (2, 9),
                                   (2, 10),
                                   (2, 11),
                                   (2, 12),
                                   (3, 9),
                                   (3, 10),
                                   (3, 11),
                                   (3, 12)],
                         'is_dummy': False},
                        {'zone_id': 4,
                         'channel': 4,
                         'sub_capture': 0,
                         'spads': [(1, 13),
                                   (1, 14),
                                   (1, 15),
                                   (1, 16),
                                   (1, 17),
                                   (2, 13),
                                   (2, 14),
                                   (2, 15),
                                   (2, 16),
                                   (2, 17),
                                   (3, 13),
                                   (3, 14),
                                   (3, 15),
                                   (3, 16),
                                   (3, 17)],
                         'is_dummy': False},
                        {'zone_id': 5,
                         'channel': 5,
                         'sub_capture': 0,
                         'spads': [(4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4)],
                         'is_dummy': False},
                        {'zone_id': 6,
                         'channel': 6,
                         'sub_capture': 0,
                         'spads': [(4, 5), (4, 6), (4, 7), (4, 8), (5, 5), (5, 6), (5, 7), (5, 8)],
                         'is_dummy': False},
                        {'zone_id': 7,
                         'channel': 7,
                         'sub_capture': 0,
                         'spads': [(4, 9), (4, 10), (4, 11), (4, 12), (5, 9), (5, 10), (5, 11), (5, 12)],
                         'is_dummy': False},
                        {'zone_id': 8,
                         'channel': 8,
                         'sub_capture': 0,
                         'spads': [(4, 13),
                                   (4, 14),
                                   (4, 15),
                                   (4, 16),
                                   (4, 17),
                                   (5, 13),
                                   (5, 14),
                                   (5, 15),
                                   (5, 16),
                                   (5, 17)],
                         'is_dummy': False},
                        {'zone_id': 9,
                         'channel': 1,
                         'sub_capture': 1,
                         'spads': [(6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4)],
                         'is_dummy': False},
                        {'zone_id': 10,
                         'channel': 2,
                         'sub_capture': 1,
                         'spads': [(6, 5), (6, 6), (6, 7), (6, 8), (7, 5), (7, 6), (7, 7), (7, 8)],
                         'is_dummy': False},
                        {'zone_id': 11,
                         'channel': 3,
                         'sub_capture': 1,
                         'spads': [(6, 9), (6, 10), (6, 11), (6, 12), (7, 9), (7, 10), (7, 11), (7, 12)],
                         'is_dummy': False},
                        {'zone_id': 12,
                         'channel': 4,
                         'sub_capture': 1,
                         'spads': [(6, 13),
                                   (6, 14),
                                   (6, 15),
                                   (6, 16),
                                   (6, 17),
                                   (7, 13),
                                   (7, 14),
                                   (7, 15),
                                   (7, 16),
                                   (7, 17)],
                         'is_dummy': False},
                        {'zone_id': 13,
                         'channel': 5,
                         'sub_capture': 1,
                         'spads': [(8, 0),
                                   (8, 1),
                                   (8, 2),
                                   (8, 3),
                                   (8, 4),
                                   (9, 0),
                                   (9, 1),
                                   (9, 2),
                                   (9, 3),
                                   (9, 4),
                                   (10, 0),
                                   (10, 1),
                                   (10, 2),
                                   (10, 3),
                                   (10, 4)],
                         'is_dummy': False},
                        {'zone_id': 14,
                         'channel': 6,
                         'sub_capture': 1,
                         'spads': [(8, 5),
                                   (8, 6),
                                   (8, 7),
                                   (8, 8),
                                   (9, 5),
                                   (9, 6),
                                   (9, 7),
                                   (9, 8),
                                   (10, 5),
                                   (10, 6),
                                   (10, 7),
                                   (10, 8)],
                         'is_dummy': False},
                        {'zone_id': 15,
                         'channel': 7,
                         'sub_capture': 1,
                         'spads': [(8, 9),
                                   (8, 10),
                                   (8, 11),
                                   (8, 12),
                                   (9, 9),
                                   (9, 10),
                                   (9, 11),
                                   (9, 12),
                                   (10, 9),
                                   (10, 10),
                                   (10, 11),
                                   (10, 12)],
                         'is_dummy': False},
                        {'zone_id': 16,
                         'channel': 8,
                         'sub_capture': 1,
                         'spads': [(8, 13),
                                   (8, 14),
                                   (8, 15),
                                   (8, 16),
                                   (8, 17),
                                   (9, 13),
                                   (9, 14),
                                   (9, 15),
                                   (9, 16),
                                   (9, 17),
                                   (10, 13),
                                   (10, 14),
                                   (10, 15),
                                   (10, 16),
                                   (10, 17)],
                         'is_dummy': False}],
              'meta': {'y_size': 10,
                       'x_size': 18,
                       'y_offset_2': 0,
                       'x_offset_2': 0,
                       'time_multiplexed': True,
                       'verified': True,
                       'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '9_zone': {'zones': [{'zone_id': 1,
                       'channel': 1,
                       'sub_capture': 0,
                       'spads': [(1, 2),
                                 (1, 3),
                                 (1, 4),
                                 (1, 5),
                                 (1, 6),
                                 (1, 7),
                                 (1, 8),
                                 (1, 9),
                                 (1, 10),
                                 (1, 11),
                                 (1, 12),
                                 (1, 13),
                                 (1, 14),
                                 (1, 15),
                                 (2, 2),
                                 (2, 3),
                                 (2, 4),
                                 (2, 5),
                                 (2, 6),
                                 (2, 7),
                                 (2, 8),
                                 (2, 9),
                                 (2, 10),
                                 (2, 11),
                                 (2, 12),
                                 (2, 13),
                                 (2, 14),
                                 (2, 15),
                                 (3, 2),
                                 (3, 3),
                                 (3, 4),
                                 (3, 5),
                                 (3, 6),
                                 (3, 7),
                                 (3, 8),
                                 (3, 9),
                                 (3, 10),
                                 (3, 11),
                                 (3, 12),
                                 (3, 13),
                                 (3, 14),
                                 (3, 15)],
                       'is_dummy': False},
                      {'zone_id': 2,
                       'channel': 2,
                       'sub_capture': 0,
                       'spads': [(4, 2),
                                 (4, 3),
                                 (4, 4),
                                 (4, 5),
                                 (5, 2),
                                 (5, 3),
                                 (5, 4),
                                 (5, 5),
                                 (6, 2),
                                 (6, 3),
                                 (6, 4),
                                 (6, 5)],
                       'is_dummy': False},
                      {'zone_id': 3,
                       'channel': 3,
                       'sub_capture': 0,
                       'spads': [(4, 6), (4, 7), (4, 8), (5, 6), (5, 7), (5, 8), (6, 6), (6, 7), (6, 8)],
                       'is_dummy': False},
                      {'zone_id': 4,
                       'channel': 4,
                       'sub_capture': 0,
                       'spads': [(4, 9), (4, 10), (4, 11), (5, 9), (5, 10), (5, 11), (6, 9), (6, 10), (6, 11)],
                       'is_dummy': False},
                      {'zone_id': 5,
                       'channel': 5,
                       'sub_capture': 0,
                       'spads': [(4, 12),
                                 (4, 13),
                                 (4, 14),
                                 (4, 15),
                                 (5, 12),
                                 (5, 13),
                                 (5, 14),
                                 (5, 15),
                                 (6, 12),
                                 (6, 13),
                                 (6, 14),
                                 (6, 15)],
                       'is_dummy': False},
                      {'zone_id': 6,
                       'channel': 6,
                       'sub_capture': 0,
                       'spads': [(7, 2),
                                 (7, 3),
                                 (7, 4),
                                 (7, 5),
                                 (8, 2),
                                 (8, 3),
                                 (8, 4),
                                 (8, 5),
                                 (9, 2),
                                 (9, 3),
                                 (9, 4),
                                 (9, 5)],
                       'is_dummy': False},
                      {'zone_id': 7,
                       'channel': 7,
                       'sub_capture': 0,
                       'spads': [(7, 6), (7, 7), (7, 8), (8, 6), (8, 7), (8, 8), (9, 6), (9, 7), (9, 8)],
                       'is_dummy': False},
                      {'zone_id': 8,
                       'channel': 8,
                       'sub_capture': 0,
                       'spads': [(7, 9), (7, 10), (7, 11), (8, 9), (8, 10), (8, 11), (9, 9), (9, 10), (9, 11)],
                       'is_dummy': False},
                      {'zone_id': 9,
                       'channel': 9,
                       'sub_capture': 0,
                       'spads': [(7, 12),
                                 (7, 13),
                                 (7, 14),
                                 (7, 15),
                                 (8, 12),
                                 (8, 13),
                                 (8, 14),
                                 (8, 15),
                                 (9, 12),
                                 (9, 13),
                                 (9, 14),
                                 (9, 15)],
                       'is_dummy': False}],
            'meta': {'y_size': 9,
                     'x_size': 14,
                     'y_offset_2': 3,
                     'x_offset_2': 0,
                     'time_multiplexed': False,
                     'verified': True,
                     'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '9_zone_v2': {'zones': [{'zone_id': 1,
                          'channel': 1,
                          'sub_capture': 0,
                          'spads': [(4, 2),
                                    (4, 3),
                                    (4, 4),
                                    (4, 5),
                                    (5, 2),
                                    (5, 3),
                                    (5, 4),
                                    (5, 5),
                                    (6, 2),
                                    (6, 3),
                                    (6, 4),
                                    (6, 5)],
                          'is_dummy': False},
                         {'zone_id': 2,
                          'channel': 2,
                          'sub_capture': 0,
                          'spads': [(4, 6), (4, 7), (4, 8), (5, 6), (5, 7), (5, 8), (6, 6), (6, 7), (6, 8)],
                          'is_dummy': False},
                         {'zone_id': 3,
                          'channel': 3,
                          'sub_capture': 0,
                          'spads': [(4, 9), (4, 10), (4, 11), (5, 9), (5, 10), (5, 11), (6, 9), (6, 10), (6, 11)],
                          'is_dummy': False},
                         {'zone_id': 4,
                          'channel': 4,
                          'sub_capture': 0,
                          'spads': [(4, 12),
                                    (4, 13),
                                    (4, 14),
                                    (4, 15),
                                    (5, 12),
                                    (5, 13),
                                    (5, 14),
                                    (5, 15),
                                    (6, 12),
                                    (6, 13),
                                    (6, 14),
                                    (6, 15)],
                          'is_dummy': False},
                         {'zone_id': 5,
                          'channel': 5,
                          'sub_capture': 0,
                          'spads': [(7, 2),
                                    (7, 3),
                                    (7, 4),
                                    (7, 5),
                                    (8, 2),
                                    (8, 3),
                                    (8, 4),
                                    (8, 5),
                                    (9, 2),
                                    (9, 3),
                                    (9, 4),
                                    (9, 5)],
                          'is_dummy': False},
                         {'zone_id': 6,
                          'channel': 6,
                          'sub_capture': 0,
                          'spads': [(7, 6), (7, 7), (7, 8), (8, 6), (8, 7), (8, 8), (9, 6), (9, 7), (9, 8)],
                          'is_dummy': False},
                         {'zone_id': 7,
                          'channel': 7,
                          'sub_capture': 0,
                          'spads': [(7, 9), (7, 10), (7, 11), (8, 9), (8, 10), (8, 11), (9, 9), (9, 10), (9, 11)],
                          'is_dummy': False},
                         {'zone_id': 8,
                          'channel': 8,
                          'sub_capture': 0,
                          'spads': [(7, 12),
                                    (7, 13),
                                    (7, 14),
                                    (7, 15),
                                    (8, 12),
                                    (8, 13),
                                    (8, 14),
                                    (8, 15),
                                    (9, 12),
                                    (9, 13),
                                    (9, 14),
                                    (9, 15)],
                          'is_dummy': False},
                         {'zone_id': 9,
                          'channel': 9,
                          'sub_capture': 0,
                          'spads': [(10, 2),
                                    (10, 3),
                                    (10, 4),
                                    (10, 5),
                                    (10, 6),
                                    (10, 7),
                                    (10, 8),
                                    (10, 9),
                                    (10, 10),
                                    (10, 11),
                                    (10, 12),
                                    (10, 13),
                                    (10, 14),
                                    (10, 15),
                                    (11, 2),
                                    (11, 3),
                                    (11, 4),
                                    (11, 5),
                                    (11, 6),
                                    (11, 7),
                                    (11, 8),
                                    (11, 9),
                                    (11, 10),
                                    (11, 11),
                                    (11, 12),
                                    (11, 13),
                                    (11, 14),
                                    (11, 15),
                                    (12, 2),
                                    (12, 3),
                                    (12, 4),
                                    (12, 5),
                                    (12, 6),
                                    (12, 7),
                                    (12, 8),
                                    (12, 9),
                                    (12, 10),
                                    (12, 11),
                                    (12, 12),
                                    (12, 13),
                                    (12, 14),
                                    (12, 15)],
                          'is_dummy': False}],
               'meta': {'y_size': 9,
                        'x_size': 14,
                        'y_offset_2': -3,
                        'x_offset_2': 0,
                        'time_multiplexed': False,
                        'verified': True,
                        'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '3x6': {'zones': [{'zone_id': 1,
                    'channel': 1,
                    'sub_capture': 0,
                    'spads': [(0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6)],
                    'is_dummy': False},
                   {'zone_id': 2,
                    'channel': 2,
                    'sub_capture': 0,
                    'spads': [(0, 7), (0, 8), (0, 9), (0, 10), (1, 7), (1, 8), (1, 9), (1, 10)],
                    'is_dummy': False},
                   {'zone_id': 3,
                    'channel': 3,
                    'sub_capture': 0,
                    'spads': [(0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15)],
                    'is_dummy': False},
                   {'zone_id': 4,
                    'channel': 4,
                    'sub_capture': 0,
                    'spads': [(2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6)],
                    'is_dummy': False},
                   {'zone_id': 5,
                    'channel': 5,
                    'sub_capture': 0,
                    'spads': [(2, 7), (2, 8), (2, 9), (2, 10), (3, 7), (3, 8), (3, 9), (3, 10)],
                    'is_dummy': False},
                   {'zone_id': 6,
                    'channel': 6,
                    'sub_capture': 0,
                    'spads': [(2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (3, 11), (3, 12), (3, 13), (3, 14), (3, 15)],
                    'is_dummy': False},
                   {'zone_id': 7,
                    'channel': 7,
                    'sub_capture': 0,
                    'spads': [(4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6)],
                    'is_dummy': False},
                   {'zone_id': 8,
                    'channel': 8,
                    'sub_capture': 0,
                    'spads': [(4, 7), (4, 8), (4, 9), (4, 10), (5, 7), (5, 8), (5, 9), (5, 10)],
                    'is_dummy': False},
                   {'zone_id': 9,
                    'channel': 9,
                    'sub_capture': 0,
                    'spads': [(4, 11), (4, 12), (4, 13), (4, 14), (4, 15), (5, 11), (5, 12), (5, 13), (5, 14), (5, 15)],
                    'is_dummy': False},
                   {'zone_id': 10,
                    'channel': 1,
                    'sub_capture': 1,
                    'spads': [(6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6)],
                    'is_dummy': False},
                   {'zone_id': 11,
                    'channel': 2,
                    'sub_capture': 1,
                    'spads': [(6, 7), (6, 8), (6, 9), (6, 10), (7, 7), (7, 8), (7, 9), (7, 10)],
                    'is_dummy': False},
                   {'zone_id': 12,
                    'channel': 3,
                    'sub_capture': 1,
                    'spads': [(6, 11), (6, 12), (6, 13), (6, 14), (6, 15), (7, 11), (7, 12), (7, 13), (7, 14), (7, 15)],
                    'is_dummy': False},
                   {'zone_id': 13,
                    'channel': 4,
                    'sub_capture': 1,
                    'spads': [(8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6)],
                    'is_dummy': False},
                   {'zone_id': 14,
                    'channel': 5,
                    'sub_capture': 1,
                    'spads': [(8, 7), (8, 8), (8, 9), (8, 10), (9, 7), (9, 8), (9, 9), (9, 10)],
                    'is_dummy': False},
                   {'zone_id': 15,
                    'channel': 6,
                    'sub_capture': 1,
                    'spads': [(8, 11), (8, 12), (8, 13), (8, 14), (8, 15), (9, 11), (9, 12), (9, 13), (9, 14), (9, 15)],
                    'is_dummy': False},
                   {'zone_id': 16,
                    'channel': 7,
                    'sub_capture': 1,
                    'spads': [(10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (11, 2), (11, 3), (11, 4), (11, 5), (11, 6)],
                    'is_dummy': False},
                   {'zone_id': 17,
                    'channel': 8,
                    'sub_capture': 1,
                    'spads': [(10, 7), (10, 8), (10, 9), (10, 10), (11, 7), (11, 8), (11, 9), (11, 10)],
                    'is_dummy': False},
                   {'zone_id': 18,
                    'channel': 9,
                    'sub_capture': 1,
                    'spads': [(10, 11),
                              (10, 12),
                              (10, 13),
                              (10, 14),
                              (10, 15),
                              (11, 11),
                              (11, 12),
                              (11, 13),
                              (11, 14),
                              (11, 15)],
                    'is_dummy': False}],
         'meta': {'y_size': 6,
                  'x_size': 14,
                  'y_offset_2': 6,
                  'x_offset_2': 0,
                  'time_multiplexed': True,
                  'verified': True,
                  'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '3x3_checker': {'zones': [{'zone_id': 1,
                            'channel': 1,
                            'sub_capture': 0,
                            'spads': [(3, 2), (3, 4), (3, 6), (4, 3), (4, 5)],
                            'is_dummy': False},
                           {'zone_id': 2,
                            'channel': 2,
                            'sub_capture': 0,
                            'spads': [(3, 8), (3, 10), (4, 7), (4, 9)],
                            'is_dummy': False},
                           {'zone_id': 3,
                            'channel': 3,
                            'sub_capture': 0,
                            'spads': [(3, 12), (3, 14), (4, 11), (4, 13), (4, 15)],
                            'is_dummy': False},
                           {'zone_id': 4,
                            'channel': 4,
                            'sub_capture': 0,
                            'spads': [(5, 2), (5, 4), (5, 6), (6, 3), (6, 5)],
                            'is_dummy': False},
                           {'zone_id': 5,
                            'channel': 5,
                            'sub_capture': 0,
                            'spads': [(5, 8), (5, 10), (6, 7), (6, 9)],
                            'is_dummy': False},
                           {'zone_id': 6,
                            'channel': 6,
                            'sub_capture': 0,
                            'spads': [(5, 12), (5, 14), (6, 11), (6, 13), (6, 15)],
                            'is_dummy': False},
                           {'zone_id': 7,
                            'channel': 7,
                            'sub_capture': 0,
                            'spads': [(7, 2), (7, 4), (7, 6), (8, 3), (8, 5)],
                            'is_dummy': False},
                           {'zone_id': 8,
                            'channel': 8,
                            'sub_capture': 0,
                            'spads': [(7, 8), (7, 10), (8, 7), (8, 9)],
                            'is_dummy': False},
                           {'zone_id': 9,
                            'channel': 9,
                            'sub_capture': 0,
                            'spads': [(7, 12), (7, 14), (8, 11), (8, 13), (8, 15)],
                            'is_dummy': False}],
                 'meta': {'y_size': 6,
                          'x_size': 14,
                          'y_offset_2': 0,
                          'x_offset_2': 0,
                          'time_multiplexed': False,
                          'verified': True,
                          'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '3x3_checker_rev': {'zones': [{'zone_id': 1,
                                'channel': 1,
                                'sub_capture': 0,
                                'spads': [(3, 3), (3, 5), (4, 2), (4, 4), (4, 6)],
                                'is_dummy': False},
                               {'zone_id': 2,
                                'channel': 2,
                                'sub_capture': 0,
                                'spads': [(3, 7), (3, 9), (4, 8), (4, 10)],
                                'is_dummy': False},
                               {'zone_id': 3,
                                'channel': 3,
                                'sub_capture': 0,
                                'spads': [(3, 11), (3, 13), (3, 15), (4, 12), (4, 14)],
                                'is_dummy': False},
                               {'zone_id': 4,
                                'channel': 4,
                                'sub_capture': 0,
                                'spads': [(5, 3), (5, 5), (6, 2), (6, 4), (6, 6)],
                                'is_dummy': False},
                               {'zone_id': 5,
                                'channel': 5,
                                'sub_capture': 0,
                                'spads': [(5, 7), (5, 9), (6, 8), (6, 10)],
                                'is_dummy': False},
                               {'zone_id': 6,
                                'channel': 6,
                                'sub_capture': 0,
                                'spads': [(5, 11), (5, 13), (5, 15), (6, 12), (6, 14)],
                                'is_dummy': False},
                               {'zone_id': 7,
                                'channel': 7,
                                'sub_capture': 0,
                                'spads': [(7, 3), (7, 5), (8, 2), (8, 4), (8, 6)],
                                'is_dummy': False},
                               {'zone_id': 8,
                                'channel': 8,
                                'sub_capture': 0,
                                'spads': [(7, 7), (7, 9), (8, 8), (8, 10)],
                                'is_dummy': False},
                               {'zone_id': 9,
                                'channel': 9,
                                'sub_capture': 0,
                                'spads': [(7, 11), (7, 13), (7, 15), (8, 12), (8, 14)],
                                'is_dummy': False}],
                     'meta': {'y_size': 6,
                              'x_size': 14,
                              'y_offset_2': 0,
                              'x_offset_2': 0,
                              'time_multiplexed': False,
                              'verified': True,
                              'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '4x4_narrow_v3': {'zones': [{'zone_id': 1,
                              'channel': 1,
                              'sub_capture': 0,
                              'spads': [(2, 2), (2, 3), (2, 4), (2, 5), (3, 2), (3, 3), (3, 4), (3, 5)],
                              'is_dummy': False},
                             {'zone_id': 2,
                              'channel': 2,
                              'sub_capture': 0,
                              'spads': [(2, 6), (2, 7), (2, 8), (3, 6), (3, 7), (3, 8)],
                              'is_dummy': False},
                             {'zone_id': 3,
                              'channel': 3,
                              'sub_capture': 0,
                              'spads': [(2, 9), (2, 10), (2, 11), (3, 9), (3, 10), (3, 11)],
                              'is_dummy': False},
                             {'zone_id': 4,
                              'channel': 4,
                              'sub_capture': 0,
                              'spads': [(2, 12), (2, 13), (2, 14), (2, 15), (3, 12), (3, 13), (3, 14), (3, 15)],
                              'is_dummy': False},
                             {'zone_id': 5,
                              'channel': 5,
                              'sub_capture': 0,
                              'spads': [(4, 2), (4, 3), (4, 4), (4, 5), (5, 2), (5, 3), (5, 4), (5, 5)],
                              'is_dummy': False},
                             {'zone_id': 6,
                              'channel': 6,
                              'sub_capture': 0,
                              'spads': [(4, 6), (4, 7), (4, 8), (5, 6), (5, 7), (5, 8)],
                              'is_dummy': False},
                             {'zone_id': 7,
                              'channel': 7,
                              'sub_capture': 0,
                              'spads': [(4, 9), (4, 10), (4, 11), (5, 9), (5, 10), (5, 11)],
                              'is_dummy': False},
                             {'zone_id': 8,
                              'channel': 8,
                              'sub_capture': 0,
                              'spads': [(4, 12), (4, 13), (4, 14), (4, 15), (5, 12), (5, 13), (5, 14), (5, 15)],
                              'is_dummy': False},
                             {'zone_id': 9,
                              'channel': 1,
                              'sub_capture': 1,
                              'spads': [(6, 2), (6, 3), (6, 4), (6, 5), (7, 2), (7, 3), (7, 4), (7, 5)],
                              'is_dummy': False},
                             {'zone_id': 10,
                              'channel': 2,
                              'sub_capture': 1,
                              'spads': [(6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8)],
                              'is_dummy': False},
                             {'zone_id': 11,
                              'channel': 3,
                              'sub_capture': 1,
                              'spads': [(6, 9), (6, 10), (6, 11), (7, 9), (7, 10), (7, 11)],
                              'is_dummy': False},
                             {'zone_id': 12,
                              'channel': 4,
                              'sub_capture': 1,
                              'spads': [(6, 12), (6, 13), (6, 14), (6, 15), (7, 12), (7, 13), (7, 14), (7, 15)],
                              'is_dummy': False},
                             {'zone_id': 13,
                              'channel': 5,
                              'sub_capture': 1,
                              'spads': [(8, 2), (8, 3), (8, 4), (8, 5), (9, 2), (9, 3), (9, 4), (9, 5)],
                              'is_dummy': False},
                             {'zone_id': 14,
                              'channel': 6,
                              'sub_capture': 1,
                              'spads': [(8, 6), (8, 7), (8, 8), (9, 6), (9, 7), (9, 8)],
                              'is_dummy': False},
                             {'zone_id': 15,
                              'channel': 7,
                              'sub_capture': 1,
                              'spads': [(8, 9), (8, 10), (8, 11), (9, 9), (9, 10), (9, 11)],
                              'is_dummy': False},
                             {'zone_id': 16,
                              'channel': 8,
                              'sub_capture': 1,
                              'spads': [(8, 12), (8, 13), (8, 14), (8, 15), (9, 12), (9, 13), (9, 14), (9, 15)],
                              'is_dummy': False}],
                   'meta': {'y_size': 8,
                            'x_size': 14,
                            'y_offset_2': 0,
                            'x_offset_2': 0,
                            'time_multiplexed': True,
                            'verified': True,
                            'verified_source': "device readback via SPAD-1/SPAD-2 page (firmware 'R'/'X' commands)"}},
 '8x8': {'zones': [{'zone_id': 1,
                    'channel': 7,
                    'sub_capture': 4,
                    'spads': [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)],
                    'is_dummy': False},
                   {'zone_id': 2,
                    'channel': 7,
                    'sub_capture': 5,
                    'spads': [(1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4)],
                    'is_dummy': False},
                   {'zone_id': 3,
                    'channel': 7,
                    'sub_capture': 6,
                    'spads': [(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6)],
                    'is_dummy': False},
                   {'zone_id': 4,
                    'channel': 7,
                    'sub_capture': 7,
                    'spads': [(1, 6), (1, 7), (1, 8), (2, 6), (2, 7), (2, 8)],
                    'is_dummy': False},
                   {'zone_id': 5,
                    'channel': 8,
                    'sub_capture': 4,
                    'spads': [(1, 9), (1, 10), (1, 11), (2, 9), (2, 10), (2, 11)],
                    'is_dummy': False},
                   {'zone_id': 6,
                    'channel': 8,
                    'sub_capture': 5,
                    'spads': [(1, 11), (1, 12), (1, 13), (2, 11), (2, 12), (2, 13)],
                    'is_dummy': False},
                   {'zone_id': 7,
                    'channel': 8,
                    'sub_capture': 6,
                    'spads': [(1, 13), (1, 14), (1, 15), (2, 13), (2, 14), (2, 15)],
                    'is_dummy': False},
                   {'zone_id': 8,
                    'channel': 8,
                    'sub_capture': 7,
                    'spads': [(1, 15), (1, 16), (1, 17), (2, 15), (2, 16), (2, 17)],
                    'is_dummy': False},
                   {'zone_id': 9,
                    'channel': 7,
                    'sub_capture': 0,
                    'spads': [(2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2)],
                    'is_dummy': False},
                   {'zone_id': 10,
                    'channel': 7,
                    'sub_capture': 1,
                    'spads': [(2, 2), (2, 3), (2, 4), (3, 2), (3, 3), (3, 4)],
                    'is_dummy': False},
                   {'zone_id': 11,
                    'channel': 7,
                    'sub_capture': 2,
                    'spads': [(2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)],
                    'is_dummy': False},
                   {'zone_id': 12,
                    'channel': 7,
                    'sub_capture': 3,
                    'spads': [(2, 6), (2, 7), (2, 8), (3, 6), (3, 7), (3, 8)],
                    'is_dummy': False},
                   {'zone_id': 13,
                    'channel': 8,
                    'sub_capture': 0,
                    'spads': [(2, 9), (2, 10), (2, 11), (3, 9), (3, 10), (3, 11)],
                    'is_dummy': False},
                   {'zone_id': 14,
                    'channel': 8,
                    'sub_capture': 1,
                    'spads': [(2, 11), (2, 12), (2, 13), (3, 11), (3, 12), (3, 13)],
                    'is_dummy': False},
                   {'zone_id': 15,
                    'channel': 8,
                    'sub_capture': 2,
                    'spads': [(2, 13), (2, 14), (2, 15), (3, 13), (3, 14), (3, 15)],
                    'is_dummy': False},
                   {'zone_id': 16,
                    'channel': 8,
                    'sub_capture': 3,
                    'spads': [(2, 15), (2, 16), (2, 17), (3, 15), (3, 16), (3, 17)],
                    'is_dummy': False},
                   {'zone_id': 17,
                    'channel': 5,
                    'sub_capture': 4,
                    'spads': [(3, 0), (3, 1), (3, 2), (4, 0), (4, 1), (4, 2)],
                    'is_dummy': False},
                   {'zone_id': 18,
                    'channel': 5,
                    'sub_capture': 5,
                    'spads': [(3, 2), (3, 3), (3, 4), (4, 2), (4, 3), (4, 4)],
                    'is_dummy': False},
                   {'zone_id': 19,
                    'channel': 5,
                    'sub_capture': 6,
                    'spads': [(3, 4), (3, 5), (3, 6), (4, 4), (4, 5), (4, 6)],
                    'is_dummy': False},
                   {'zone_id': 20,
                    'channel': 5,
                    'sub_capture': 7,
                    'spads': [(3, 6), (3, 7), (3, 8), (4, 6), (4, 7), (4, 8)],
                    'is_dummy': False},
                   {'zone_id': 21,
                    'channel': 6,
                    'sub_capture': 4,
                    'spads': [(3, 9), (3, 10), (3, 11), (4, 9), (4, 10), (4, 11)],
                    'is_dummy': False},
                   {'zone_id': 22,
                    'channel': 6,
                    'sub_capture': 5,
                    'spads': [(3, 11), (3, 12), (3, 13), (4, 11), (4, 12), (4, 13)],
                    'is_dummy': False},
                   {'zone_id': 23,
                    'channel': 6,
                    'sub_capture': 6,
                    'spads': [(3, 13), (3, 14), (3, 15), (4, 13), (4, 14), (4, 15)],
                    'is_dummy': False},
                   {'zone_id': 24,
                    'channel': 6,
                    'sub_capture': 7,
                    'spads': [(3, 15), (3, 16), (3, 17), (4, 15), (4, 16), (4, 17)],
                    'is_dummy': False},
                   {'zone_id': 25,
                    'channel': 5,
                    'sub_capture': 0,
                    'spads': [(4, 0), (4, 1), (4, 2), (5, 0), (5, 1), (5, 2)],
                    'is_dummy': False},
                   {'zone_id': 26,
                    'channel': 5,
                    'sub_capture': 1,
                    'spads': [(4, 2), (4, 3), (4, 4), (5, 2), (5, 3), (5, 4)],
                    'is_dummy': False},
                   {'zone_id': 27,
                    'channel': 5,
                    'sub_capture': 2,
                    'spads': [(4, 4), (4, 5), (4, 6), (5, 4), (5, 5), (5, 6)],
                    'is_dummy': False},
                   {'zone_id': 28,
                    'channel': 5,
                    'sub_capture': 3,
                    'spads': [(4, 6), (4, 7), (4, 8), (5, 6), (5, 7), (5, 8)],
                    'is_dummy': False},
                   {'zone_id': 29,
                    'channel': 6,
                    'sub_capture': 0,
                    'spads': [(4, 9), (4, 10), (4, 11), (5, 9), (5, 10), (5, 11)],
                    'is_dummy': False},
                   {'zone_id': 30,
                    'channel': 6,
                    'sub_capture': 1,
                    'spads': [(4, 11), (4, 12), (4, 13), (5, 11), (5, 12), (5, 13)],
                    'is_dummy': False},
                   {'zone_id': 31,
                    'channel': 6,
                    'sub_capture': 2,
                    'spads': [(4, 13), (4, 14), (4, 15), (5, 13), (5, 14), (5, 15)],
                    'is_dummy': False},
                   {'zone_id': 32,
                    'channel': 6,
                    'sub_capture': 3,
                    'spads': [(4, 15), (4, 16), (4, 17), (5, 15), (5, 16), (5, 17)],
                    'is_dummy': False},
                   {'zone_id': 33,
                    'channel': 3,
                    'sub_capture': 4,
                    'spads': [(6, 0), (6, 1), (6, 2), (7, 0), (7, 1), (7, 2)],
                    'is_dummy': False},
                   {'zone_id': 34,
                    'channel': 3,
                    'sub_capture': 5,
                    'spads': [(6, 2), (6, 3), (6, 4), (7, 2), (7, 3), (7, 4)],
                    'is_dummy': False},
                   {'zone_id': 35,
                    'channel': 3,
                    'sub_capture': 6,
                    'spads': [(6, 4), (6, 5), (6, 6), (7, 4), (7, 5), (7, 6)],
                    'is_dummy': False},
                   {'zone_id': 36,
                    'channel': 3,
                    'sub_capture': 7,
                    'spads': [(6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8)],
                    'is_dummy': False},
                   {'zone_id': 37,
                    'channel': 4,
                    'sub_capture': 4,
                    'spads': [(6, 9), (6, 10), (6, 11), (7, 9), (7, 10), (7, 11)],
                    'is_dummy': False},
                   {'zone_id': 38,
                    'channel': 4,
                    'sub_capture': 5,
                    'spads': [(6, 11), (6, 12), (6, 13), (7, 11), (7, 12), (7, 13)],
                    'is_dummy': False},
                   {'zone_id': 39,
                    'channel': 4,
                    'sub_capture': 6,
                    'spads': [(6, 13), (6, 14), (6, 15), (7, 13), (7, 14), (7, 15)],
                    'is_dummy': False},
                   {'zone_id': 40,
                    'channel': 4,
                    'sub_capture': 7,
                    'spads': [(6, 15), (6, 16), (6, 17), (7, 15), (7, 16), (7, 17)],
                    'is_dummy': False},
                   {'zone_id': 41,
                    'channel': 3,
                    'sub_capture': 0,
                    'spads': [(7, 0), (7, 1), (7, 2), (8, 0), (8, 1), (8, 2)],
                    'is_dummy': False},
                   {'zone_id': 42,
                    'channel': 3,
                    'sub_capture': 1,
                    'spads': [(7, 2), (7, 3), (7, 4), (8, 2), (8, 3), (8, 4)],
                    'is_dummy': False},
                   {'zone_id': 43,
                    'channel': 3,
                    'sub_capture': 2,
                    'spads': [(7, 4), (7, 5), (7, 6), (8, 4), (8, 5), (8, 6)],
                    'is_dummy': False},
                   {'zone_id': 44,
                    'channel': 3,
                    'sub_capture': 3,
                    'spads': [(7, 6), (7, 7), (7, 8), (8, 6), (8, 7), (8, 8)],
                    'is_dummy': False},
                   {'zone_id': 45,
                    'channel': 4,
                    'sub_capture': 0,
                    'spads': [(7, 9), (7, 10), (7, 11), (8, 9), (8, 10), (8, 11)],
                    'is_dummy': False},
                   {'zone_id': 46,
                    'channel': 4,
                    'sub_capture': 1,
                    'spads': [(7, 11), (7, 12), (7, 13), (8, 11), (8, 12), (8, 13)],
                    'is_dummy': False},
                   {'zone_id': 47,
                    'channel': 4,
                    'sub_capture': 2,
                    'spads': [(7, 13), (7, 14), (7, 15), (8, 13), (8, 14), (8, 15)],
                    'is_dummy': False},
                   {'zone_id': 48,
                    'channel': 4,
                    'sub_capture': 3,
                    'spads': [(7, 15), (7, 16), (7, 17), (8, 15), (8, 16), (8, 17)],
                    'is_dummy': False},
                   {'zone_id': 49,
                    'channel': 1,
                    'sub_capture': 4,
                    'spads': [(8, 0), (8, 1), (8, 2), (9, 0), (9, 1), (9, 2)],
                    'is_dummy': False},
                   {'zone_id': 50,
                    'channel': 1,
                    'sub_capture': 5,
                    'spads': [(8, 2), (8, 3), (8, 4), (9, 2), (9, 3), (9, 4)],
                    'is_dummy': False},
                   {'zone_id': 51,
                    'channel': 1,
                    'sub_capture': 6,
                    'spads': [(8, 4), (8, 5), (8, 6), (9, 4), (9, 5), (9, 6)],
                    'is_dummy': False},
                   {'zone_id': 52,
                    'channel': 1,
                    'sub_capture': 7,
                    'spads': [(8, 6), (8, 7), (8, 8), (9, 6), (9, 7), (9, 8)],
                    'is_dummy': False},
                   {'zone_id': 53,
                    'channel': 2,
                    'sub_capture': 4,
                    'spads': [(8, 9), (8, 10), (8, 11), (9, 9), (9, 10), (9, 11)],
                    'is_dummy': False},
                   {'zone_id': 54,
                    'channel': 2,
                    'sub_capture': 5,
                    'spads': [(8, 11), (8, 12), (8, 13), (9, 11), (9, 12), (9, 13)],
                    'is_dummy': False},
                   {'zone_id': 55,
                    'channel': 2,
                    'sub_capture': 6,
                    'spads': [(8, 13), (8, 14), (8, 15), (9, 13), (9, 14), (9, 15)],
                    'is_dummy': False},
                   {'zone_id': 56,
                    'channel': 2,
                    'sub_capture': 7,
                    'spads': [(8, 15), (8, 16), (8, 17), (9, 15), (9, 16), (9, 17)],
                    'is_dummy': False},
                   {'zone_id': 57,
                    'channel': 1,
                    'sub_capture': 0,
                    'spads': [(9, 0), (9, 1), (9, 2), (10, 0), (10, 1), (10, 2)],
                    'is_dummy': False},
                   {'zone_id': 58,
                    'channel': 1,
                    'sub_capture': 1,
                    'spads': [(9, 2), (9, 3), (9, 4), (10, 2), (10, 3), (10, 4)],
                    'is_dummy': False},
                   {'zone_id': 59,
                    'channel': 1,
                    'sub_capture': 2,
                    'spads': [(9, 4), (9, 5), (9, 6), (10, 4), (10, 5), (10, 6)],
                    'is_dummy': False},
                   {'zone_id': 60,
                    'channel': 1,
                    'sub_capture': 3,
                    'spads': [(9, 6), (9, 7), (9, 8), (10, 6), (10, 7), (10, 8)],
                    'is_dummy': False},
                   {'zone_id': 61,
                    'channel': 2,
                    'sub_capture': 0,
                    'spads': [(9, 9), (9, 10), (9, 11), (10, 9), (10, 10), (10, 11)],
                    'is_dummy': False},
                   {'zone_id': 62,
                    'channel': 2,
                    'sub_capture': 1,
                    'spads': [(9, 11), (9, 12), (9, 13), (10, 11), (10, 12), (10, 13)],
                    'is_dummy': False},
                   {'zone_id': 63,
                    'channel': 2,
                    'sub_capture': 2,
                    'spads': [(9, 13), (9, 14), (9, 15), (10, 13), (10, 14), (10, 15)],
                    'is_dummy': False},
                   {'zone_id': 64,
                    'channel': 2,
                    'sub_capture': 3,
                    'spads': [(9, 15), (9, 16), (9, 17), (10, 15), (10, 16), (10, 17)],
                    'is_dummy': False}],
         'meta': {'y_size': 10,
                  'x_size': 18,
                  'y_offset_2': 0,
                  'x_offset_2': 0,
                  'time_multiplexed': True,
                  'verified': True,
                  'verified_source': 'AMS DS000693 §7.4 Fig 32 (8x8 = 4 sequential 4x4 captures, each output = 6 SPADs '
                                     'in 2×3 block) + AMS firmware pixel_map in sensor.py',
                  'note': 'TMF8828 8x8 = 4 sequential 4x4 captures stitched into 64 outputs. Per AMS spec, ALL 10 mask '
                          'rows (visual rows 1..10) and all 18 cols are used across the 4 captures combined. Only the '
                          'macro-extension rows (visual 0 and 11) are unused. Each output cell aggregates 6 SPADs in a '
                          '2×3 block; adjacent output cells share 1 SPAD row or column.'}}}
